#Importing libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime

#Importing dataset

In [2]:
ds= pd.read_csv(r'C:\Users\mycom\Desktop\UK_Traffic_Accidents_2015.csv')
#To view all columns
pd.options.display.max_columns = None

D:\AnacondaInstall\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
ds

Accident_Index  Location_Easting_OSGR  Location_Northing_OSGR  \
0       201501BS70001               525130.0                180050.0   
1       201501BS70002               526530.0                178560.0   
2       201501BS70004               524610.0                181080.0   
3       201501BS70005               524420.0                181080.0   
4       201501BS70008               524630.0                179040.0   
5       201501BS70009               525480.0                179530.0   
6       201501BS70010               526890.0                178940.0   
7       201501BS70011               527590.0                178660.0   
8       201501BS70012               524170.0                180930.0   
9       201501BS70013               525010.0                181200.0   
10      201501BS70014               523850.0                181450.0   
11      201501BS70015               526110.0                179650.0   
12      201501BS70016               526970.0                178510.0   
13      201501BS70017               525350.0                178640.0   
14      201501BS70018               527370.0                178170.0   
15      201501BS70019               527370.0                178180.0   
16      201501BS70020               524020.0                181050.0   
17      201501BS70022               526200.0                177720.0   
18      201501BS70023               524450.0                181560.0   
19      201501BS70024               526940.0                178480.0   
20      201501BS70026               527600.0                179480.0   
21      201501BS70027               525560.0                178170.0   
22      201501BS70029               525510.0                178130.0   
23      201501BS70030               523910.0                181390.0   
24      201501BS70033               526090.0                177600.0   
25      201501BS70034               527560.0                179160.0   
26      201501BS70035               527950.0                178890.0   
27      201501BS70036               525390.0                180190.0   
28      201501BS70037               527350.0                177640.0   
29      201501BS70038               527340.0                178160.0   
...               ...                    ...                     ...   
140026  2015984126215               338953.0                576296.0   
140027  2015984126815               317327.0                566149.0   
140028  2015984126915               318128.0                575574.0   
140029  2015984127315               320333.0                567053.0   
140030  2015984127515               319848.0                566515.0   
140031  2015984127615               338620.0                595149.0   
140032  2015984128215               327982.0                570650.0   
140033  2015984128515               318980.0                575210.0   
140034  2015984129115               309715.0                598908.0   
140035  2015984129715               330766.0                567430.0   
140036  2015984130315               312312.0                605860.0   
140037  2015984130815               310460.0                604532.0   
140038  2015984131215               328774.0                567001.0   
140039  2015984132215               320174.0                566497.0   
140040  2015984132315               325193.0                568986.0   
140041  2015984132815               315619.0                578498.0   
140042  2015984133015               319506.0                566586.0   
140043  2015984133115               308738.0                579979.0   
140044  2015984133815               314076.0                578925.0   
140045  2015984134815               310142.0                596869.0   
140046  2015984135815               338928.0                576364.0   
140047  2015984136815               324728.0                566339.0   
140048  2015984137515               327369.0                566993.0   
140049  2015984137615               319301.0   

#A quick look at data info

In [4]:
# what columns do we have and Which data type?
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140056 entries, 0 to 140055
Data columns (total 32 columns):
Accident_Index                                 140056 non-null object
Location_Easting_OSGR                          140029 non-null float64
Location_Northing_OSGR                         140029 non-null float64
Longitude                                      140029 non-null float64
Latitude                                       140029 non-null float64
Police_Force                                   140056 non-null int64
Accident_Severity                              140056 non-null int64
Number_of_Vehicles                             140056 non-null int64
Number_of_Casualties                           140056 non-null int64
Date                                           140056 non-null object
Day_of_Week                                    140056 non-null int64
Time                                           140038 non-null object
Local_Authority_(District)                     140

In [5]:
#How many rows and columns?
ds.shape

(140056, 32)

In [6]:
# Take a look at the numeric ranges
ds.describe(include='all')
#some give NaN because The describe method for numeric columns doesn't list the number of unique values

Accident_Index  Location_Easting_OSGR  Location_Northing_OSGR  \
count     1.400560e+05          140029.000000            1.400290e+05   
unique    1.400560e+05                    NaN                     NaN   
top       2.015440e+12                    NaN                     NaN   
freq      1.000000e+00                    NaN                     NaN   
mean               NaN          446913.896086            2.899043e+05   
std                NaN           94893.264196            1.577932e+05   
min                NaN           70860.000000            1.062800e+04   
25%                NaN          385626.000000            1.766380e+05   
50%                NaN          451460.000000            2.408860e+05   
75%                NaN          526760.000000            3.911840e+05   
max                NaN          655282.000000            1.197917e+06   

            Longitude       Latitude   Police_Force  Accident_Severity  \
count   140029.000000  140029.000000  140056.000000      140056.000000   
unique            NaN            NaN            NaN                NaN   
top               NaN            NaN            NaN                NaN   
freq              NaN            NaN            NaN                NaN   
mean        -1.330458      52.496743      29.902046           2.833852   
std          1.393585       1.420984      25.217637           0.402020   
min         -7.422915      49.915618       1.000000           1.000000   
25%         -2.216068      51.475197       6.000000           3.000000   
50%         -1.236156      52.051875      30.000000           3.000000   
75%         -0.172506      53.414614      45.000000           3.000000   
max          1.758443      60.661117      98.000000           3.000000   

        Number_of_Vehicles  Number_of_Casualties        Date    Day_of_Week  \
count        140056.000000         140056.000000      140056  140056.000000   
unique                 NaN                   NaN         365            NaN   
top                    NaN                   NaN  05/11/2015            NaN   
freq                   NaN                   NaN         535            NaN   
mean              1.841014              1.329390         NaN       4.094962   
std               0.710046              0.795427         NaN       1.911279   
min               1.000000              1.000000         NaN       1.000000   
25%               1.000000              1.000000         NaN       2.000000   
50%               2.000000              1.000000         NaN       4.000000   
75%               2.000000              1.000000         NaN       6.000000   
max              37.000000             38.000000         NaN       7.000000   

          Time  Local_Authority_(District) Local_Authority_(Highway)  \
count   140038               140056.000000                    140056   
unique    1439                         NaN                       207   
top      17:00                         NaN                 E10000016   
freq      1347                         NaN                      4222   
mean       NaN                  343.648905                       NaN   
std        NaN                  258.438367                       NaN   
min        NaN                    1.000000                       NaN   
25%        NaN                  104.000000                       NaN   
50%        NaN                  323.000000                       NaN   
75%        NaN                  517.000000                       NaN   
max        NaN                  941.000000                       NaN   

        1st_Road_Class  1st_Road_Number      Road_Type    Speed_limit  \
count    140056.000000    140056.000000  140056.000000  140056.000000   
unique             NaN              NaN            NaN            NaN   
top                NaN              NaN            NaN            NaN   
freq               NaN              NaN            NaN            NaN   
mean          4.102966       982.268657       5.169182      38.

In [7]:
#so, converting to category
ds1= ds.apply(pd.Categorical, axis=0)

In [8]:
ds1.describe(include='all')

Accident_Index  Location_Easting_OSGR  Location_Northing_OSGR  \
count          140056               140029.0                140029.0   
unique         140056                89880.0                 93322.0   
top     2015984141415               533650.0                181310.0   
freq                1                   49.0                    41.0   

           Longitude       Latitude  Police_Force  Accident_Severity  \
count   140029.00000  140029.000000        140056             140056   
unique  133316.00000  131977.000000            51                  3   
top         -0.15588      51.489589             1                  3   
freq         8.00000       8.000000         24886             118402   

        Number_of_Vehicles  Number_of_Casualties        Date  Day_of_Week  \
count               140056                140056      140056       140056   
unique                  16                    22         365            7   
top                      2                     1  05/11/2015            6   
freq                 84615                109395         535        22374   

          Time  Local_Authority_(District) Local_Authority_(Highway)  \
count   140038                      140056                    140056   
unique    1439                         380                       207   
top      17:00                         300                 E10000016   
freq      1347                        2970                      4222   

        1st_Road_Class  1st_Road_Number  Road_Type  Speed_limit  \
count           140056           140056     140056       140056   
unique               6             4340          6            8   
top                  3                0          6           30   
freq             64280            39405     105066        89627   

        Junction_Detail  Junction_Control  2nd_Road_Class  2nd_Road_Number  \
count            140056            140056          140056           140056   
unique               10                 5               7             3795   
top                   0                 4               6                0   
freq              55927             68655           57088           110543   

        Pedestrian_Crossing-Human_Control  \
count                              140056   
unique                                  4   
top                                     0   
freq                               139201   

        Pedestrian_Crossing-Physical_Facilities  Light_Conditions  \
count                                    140056            140056   
unique                                        7                 5   
top                                           0                 1   
freq                                     113486            102608   

        Weather_Conditions  Road_Surface_Conditions  \
count               140056                   140056   
unique                   9                        6   
top                      1                        1   
freq                113949                   101355   

        Special_Conditions_at_Site  Carriageway_Hazards  Urban_or_Rural_Area  \
count                       140056               140056               140056   
unique                           9                    7                    2   
top                              0                    0                    1   
freq                        136823               137749                92080   

        Did_Police_Officer_Attend_Scene_of_Accident LSOA_of_Accident_Location  
count                                        140056                    131159  
unique                                            4                     28737  
top                                               1                 E01032739  
freq                                         112607                       236

#check for duplicates

In [9]:
ds[ds.duplicated()]
sum(ds.duplicated())

0

#Dropping unnecessary columns

In [10]:
ds.drop(['Location_Easting_OSGR', 'Location_Northing_OSGR', 'LSOA_of_Accident_Location', '1st_Road_Class','1st_Road_Number',
         '2nd_Road_Number', '2nd_Road_Class'], axis='columns', inplace=True)

In [11]:
ds.shape

(140056, 25)

#check for null values

In [12]:
#Is there null values? and how many?
ds.isnull().sum()

Accident_Index                                  0
Longitude                                      27
Latitude                                       27
Police_Force                                    0
Accident_Severity                               0
Number_of_Vehicles                              0
Number_of_Casualties                            0
Date                                            0
Day_of_Week                                     0
Time                                           18
Local_Authority_(District)                      0
Local_Authority_(Highway)                       0
Road_Type                                       0
Speed_limit                                     0
Junction_Detail                                 0
Junction_Control                                0
Pedestrian_Crossing-Human_Control               0
Pedestrian_Crossing-Physical_Facilities         0
Light_Conditions                                0
Weather_Conditions                              0


#Fill or drop null values

In [13]:
# Filling null values for location as 0.0
ds['Longitude'].fillna(0.0, inplace=True)
ds['Latitude'].fillna(0.0, inplace=True)

In [14]:
#droping null values for Time 
ds.dropna(inplace=True)

In [15]:
ds.shape

(140038, 25)

#checking unique values in some columns


In [16]:
ds['Accident_Severity'].unique()

array([3, 2, 1], dtype=int64)

In [17]:
ds['Day_of_Week'].unique()

array([2, 3, 6, 5, 1, 4, 7], dtype=int64)

In [18]:
ds['Urban_or_Rural_Area'].unique()

array([1, 2], dtype=int64)

In [19]:
ds['Road_Type'].unique()

array([6, 1, 3, 2, 7, 9], dtype=int64)

In [20]:
ds['Junction_Detail'].unique()

array([ 3,  2,  6,  0,  8,  1,  7,  9,  5, -1], dtype=int64)

In [21]:
ds['Junction_Control'].unique()

array([ 4,  2, -1,  3,  1], dtype=int64)

In [22]:
ds['Pedestrian_Crossing-Human_Control'].unique()

array([ 0,  1,  2, -1], dtype=int64)

In [23]:
ds['Pedestrian_Crossing-Physical_Facilities'].unique()

array([ 0,  1,  5,  4,  8,  7, -1], dtype=int64)

In [24]:
ds['Did_Police_Officer_Attend_Scene_of_Accident'].unique()

array([ 1,  2,  3, -1], dtype=int64)

In [25]:
ds['Light_Conditions'].unique()

array([4, 1, 6, 7, 5], dtype=int64)

In [26]:
ds['Weather_Conditions'].unique()

array([1, 2, 8, 7, 5, 9, 4, 6, 3], dtype=int64)

In [27]:
ds['Road_Surface_Conditions'].unique()

array([ 1,  2,  4,  3,  5, -1], dtype=int64)

In [28]:
ds['Special_Conditions_at_Site'].unique()

array([ 0,  4,  2,  1,  6,  5,  3,  7, -1], dtype=int64)

In [29]:
ds['Carriageway_Hazards'].unique()

array([ 0,  2,  6,  7,  1,  3, -1], dtype=int64)

#changing codes to labels

In [30]:
ds['Accident_Severity'].replace([1, 2, 3],['Fatal', 'Serious', 'Slight'], inplace=True)
ds['Day_of_Week'].replace([1,2,3,4,5,6,7],['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], 
                          inplace=True)
ds['Urban_or_Rural_Area'].replace([1, 2], ['Urban', 'Rural'], inplace=True)
ds['Road_Type'].replace([1, 2, 3, 6, 7, 9], ['Roundabout', 'One way street', 'Dual carriageway', 'Single carriageway',
                                            'Slip road', 'Unknown'], inplace=True)
ds['Junction_Detail'].replace([3,  2,  6,  0,  8,  1,  7,  9,  5, -1], ['T or staggered junction', 'Mini-roundabout', 'Crossroads',
                                                                       'Not at junction or within 20 metres', 'Private drive or entrance',
                                                                       'Roundabout', 'More than 4 arms (not roundabout)', 'Other junction',
                                                                       'Slip road', 'Data missing or out of range'], inplace=True)
ds['Junction_Control'].replace([4,  2, -1,  3,  1], ['Give way or uncontrolled', 'Auto traffic signal', 'Data missing or out of range',
                                                    'Stop sign', 'Authorised person'], inplace=True)
ds['Pedestrian_Crossing-Human_Control'].replace([0,  1,  2, -1], ['None within 50 metres', 'Control by school crossing patrol',
                                                                 'Control by other authorised person', 'Data missing or out of range'], 
                                                inplace=True)
ds['Pedestrian_Crossing-Physical_Facilities'].replace([0,  1,  5,  4,  8,  7, -1], ['No physical crossing facilities within 50 metres',
                                                                                    'Zebra', 'Pedestrian phase at traffic signal junction',
                                                                                   'Pelican, puffin, toucan or similar non-junction pedestrian light crossing',
                                                                                   'Central refuge', 'Footbridge or subway', 'Data missing or out of range'], 
                                                      inplace=True)
ds['Did_Police_Officer_Attend_Scene_of_Accident'].replace([1,  2,  3, -1], ['Yes', 'No', 'accident was reported using a self completion form',
                                                                           'data missing'], inplace=True)
ds['Light_Conditions'].replace([4, 1, 6, 7, 5], ['Darkness - lights lit', 'Daylight', 'Darkness - no lighting',
                                                'Darkness - lighting unknown', 'Darkness - lights unlit'], inplace=True)
ds['Weather_Conditions'].replace([1, 2, 8, 7, 5, 9, 4, 6, 3], ['Fine no high winds', 'Raining no high winds', 'Other',
                                                              'Fog or mist', 'Raining + high winds', 'unknown',
                                                               'Fine + high winds', 'Snowing + high winds', 
                                                               'Snowing no high winds'], inplace=True)
ds['Road_Surface_Conditions'].replace([1,  2,  4,  3,  5, -1], ['Dry', 'Wet or damp', 'Frost or ice', 'Snow', 
                                                                'Flood over 3cm deep', 'Data missing or out of range'], 
                                      inplace=True)
ds['Special_Conditions_at_Site'].replace([ 0,  4,  2,  1,  6,  5,  3,  7, -1], ['None', 'Roadworks', 'Auto signal part defective',
                                                                               'Auto traffic signal out', 'Oil or diesel',
                                                                               'Road surface defective', 'Road sign or marking defective or obscured',
                                                                               'Mud', 'Data missing or out of range'], inplace=True)
ds['Carriageway_Hazards'].replace([0,  2,  6,  7,  1,  3, -1], ['None', 'Other object on road', 'Pedestrian in carriageway',
                                                               'Any animal in carriageway', 'Vehicle load on road',
                                                               'Previous accident', 'Data missing or out of range'], 
                                  inplace=True)

In [31]:
police_force= pd.read_csv(r'C:\Users\mycom\Desktop\Police_Force.csv')
ds['Police_Force']  = ds['Police_Force'].map(police_force.set_index('code').to_dict()['label'])

In [32]:
district= pd.read_csv(r'C:\Users\mycom\Desktop\Local_Authority_District.csv')
ds['Local_Authority_(District)'] = ds['Local_Authority_(District)'].map(district.set_index('code').to_dict()['label'])

In [33]:
highway= pd.read_csv(r'C:\Users\mycom\Desktop\Local_Authority_Highway.csv')
ds['Local_Authority_(Highway)']  = ds['Local_Authority_(Highway)'].map(highway.set_index('Code').to_dict()['Label'])

#set Accident index as index

In [34]:
ds.set_index('Accident_Index', inplace=True)

In [35]:
ds

Longitude   Latitude           Police_Force Accident_Severity  \
Accident_Index                                                                  
201501BS70001   -0.198465  51.505538    Metropolitan Police            Slight   
201501BS70002   -0.178838  51.491836    Metropolitan Police            Slight   
201501BS70004   -0.205590  51.514910    Metropolitan Police            Slight   
201501BS70005   -0.208327  51.514952    Metropolitan Police            Slight   
201501BS70008   -0.206022  51.496572    Metropolitan Police           Serious   
201501BS70009   -0.193610  51.500788    Metropolitan Police            Slight   
201501BS70010   -0.173519  51.495171    Metropolitan Police            Slight   
201501BS70011   -0.163542  51.492497    Metropolitan Police            Slight   
201501BS70012   -0.211980  51.513659    Metropolitan Police            Slight   
201501BS70013   -0.199786  51.515900    Metropolitan Police            Slight   
201501BS70014   -0.216407  51.518402    Metropolitan Police            Slight   
201501BS70015   -0.184495  51.501726    Metropolitan Police            Slight   
201501BS70016   -0.172522  51.491289    Metropolitan Police            Slight   
201501BS70017   -0.195797  51.492818    Metropolitan Police            Slight   
201501BS70018   -0.166886  51.488143    Metropolitan Police            Slight   
201501BS70019   -0.166882  51.488233    Metropolitan Police            Slight   
201501BS70020   -0.214099  51.514770    Metropolitan Police            Slight   
201501BS70022   -0.183889  51.484361    Metropolitan Police            Slight   
201501BS70023   -0.207725  51.519259    Metropolitan Police            Slight   
201501BS70024   -0.172964  51.491026    Metropolitan Police            Slight   
201501BS70026   -0.163102  51.499864    Metropolitan Police           Serious   
201501BS70027   -0.192941  51.488548    Metropolitan Police            Slight   
201501BS70029   -0.193675  51.488199    Metropolitan Police            Slight   
201501BS70030   -0.215564  51.517850    Metropolitan Police            Slight   
201501BS70033   -0.185515  51.483307    Metropolitan Police            Slight   
201501BS70034   -0.163793  51.496997    Metropolitan Police            Slight   
201501BS70035   -0.158276  51.494483    Metropolitan Police            Slight   
201501BS70036   -0.194671  51.506739    Metropolitan Police            Slight   
201501BS70037   -0.167365  51.483385    Metropolitan Police            Slight   
201501BS70038   -0.167321  51.488060    Metropolitan Police            Slight   
...                   ...        ...                    ...               ...   
2015984126215   -2.957692  55.077345  Dumfries and Galloway            Slight   
2015984126815   -3.293388  54.983052  Dumfries and Galloway            Slight   
2015984126915   -3.283579  55.067857  Dumfries and Galloway            Slight   
2015984127315   -3.246680  54.991664  Dumfries and Galloway            Slight   
2015984127515   -3.254108  54.986752  Dumfries and Galloway            Slight   
2015984127615   -2.966998  55.246691  Dumfries and Galloway            Slight   
2015984128215   -3.128065  55.025147  Dumfries and Galloway             Fatal   
2015984128515   -3.270137  55.064727  Dumfries and Galloway           Serious   
2015984129115   -3.422724  55.276010  Dumfries and Galloway            Slight   
2015984129715   -3.083745  54.996613  Dumfries and Galloway            Slight   
2015984130315   -3.384031  55.338930  Dumfries and Galloway            Slight   
2015984130815   -3.412795  55.326666  Dumfries and Galloway           Serious   
2015984131215   -3.114769  54.992477  Dumfries and Galloway            Slight   
2015984132215   -3.249009  54.986643  Dumfries and Galloway            Slight   
2015984132315   -3.171246  55.009785  Dumfries and Galloway            Slight   
2015984132815   -3.323723  55.093705  Dumfries and Galloway           Serious   
2015984133015   -3.259471  54.987335  Dumfries 

#How many Data missing or out of range values

In [36]:
#how many Data missing or out of range values in Junction_Detail? 1
ds.groupby('Junction_Detail')['Junction_Detail'].count()

Junction_Detail
Crossroads                             13762
Data missing or out of range               1
Mini-roundabout                         1899
More than 4 arms (not roundabout)        999
Not at junction or within 20 metres    55918
Other junction                          3101
Private drive or entrance               5252
Roundabout                             12422
Slip road                               2032
T or staggered junction                44652
Name: Junction_Detail, dtype: int64

In [37]:
#how many Data missing or out of range values in Junction_Control? 56061
ds.groupby('Junction_Control')['Junction_Control'].count()

Junction_Control
Authorised person                 171
Auto traffic signal             14455
Data missing or out of range    56061
Give way or uncontrolled        68648
Stop sign                         703
Name: Junction_Control, dtype: int64

In [38]:
#how many Data missing or out of range values in Pedestrian_Crossing-Human_Control? 140
ds.groupby('Pedestrian_Crossing-Human_Control')['Pedestrian_Crossing-Human_Control'].count()

Pedestrian_Crossing-Human_Control
Control by other authorised person       433
Control by school crossing patrol        282
Data missing or out of range             140
None within 50 metres                 139183
Name: Pedestrian_Crossing-Human_Control, dtype: int64

In [39]:
#how many Data missing or out of range values in Pedestrian_Crossing-Physical_Facilities? 127
ds.groupby('Pedestrian_Crossing-Physical_Facilities')['Pedestrian_Crossing-Physical_Facilities'].count()

Pedestrian_Crossing-Physical_Facilities
Central refuge                                                                 3157
Data missing or out of range                                                    127
Footbridge or subway                                                            392
No physical crossing facilities within 50 metres                             113469
Pedestrian phase at traffic signal junction                                   10865
Pelican, puffin, toucan or similar non-junction pedestrian light crossing      7751
Zebra                                                                          4277
Name: Pedestrian_Crossing-Physical_Facilities, dtype: int64

In [40]:
#how many Data missing values in Did_Police_Officer_Attend_Scene_of_Accident? 8
ds.groupby('Did_Police_Officer_Attend_Scene_of_Accident')['Did_Police_Officer_Attend_Scene_of_Accident'].count()

Did_Police_Officer_Attend_Scene_of_Accident
No                                                     27059
Yes                                                   112594
accident was reported using a self completion form       377
data missing                                               8
Name: Did_Police_Officer_Attend_Scene_of_Accident, dtype: int64

In [41]:
#how many Data missing or out of range values in Road_Surface_Conditions? 284
ds.groupby('Road_Surface_Conditions')['Road_Surface_Conditions'].count()

Road_Surface_Conditions
Data missing or out of range       284
Dry                             101343
Flood over 3cm deep                184
Frost or ice                      1460
Snow                               534
Wet or damp                      36233
Name: Road_Surface_Conditions, dtype: int64

In [42]:
#how many Data missing or out of range values in Special_Conditions_at_Site? 106
ds.groupby('Special_Conditions_at_Site')['Special_Conditions_at_Site'].count()

Special_Conditions_at_Site
Auto signal part defective                        51
Auto traffic signal out                          212
Data missing or out of range                     106
Mud                                              424
None                                          136805
Oil or diesel                                    384
Road sign or marking defective or obscured       160
Road surface defective                           299
Roadworks                                       1597
Name: Special_Conditions_at_Site, dtype: int64

In [43]:
#how many Data missing or out of range values in Carriageway_Hazards? 95
ds.groupby('Carriageway_Hazards')['Carriageway_Hazards'].count()

Carriageway_Hazards
Any animal in carriageway          610
Data missing or out of range        95
None                            137731
Other object on road               929
Pedestrian in carriageway          307
Previous accident                  204
Vehicle load on road               162
Name: Carriageway_Hazards, dtype: int64

#Converting date column to datetime and adding month column

In [44]:
pd.to_datetime(ds.Date)

ds['Date'] = pd.to_datetime(ds['Date'])
ds['Month'] = ds['Date'].dt.month

#Viewing data

In [45]:
ds

Longitude   Latitude           Police_Force Accident_Severity  \
Accident_Index                                                                  
201501BS70001   -0.198465  51.505538    Metropolitan Police            Slight   
201501BS70002   -0.178838  51.491836    Metropolitan Police            Slight   
201501BS70004   -0.205590  51.514910    Metropolitan Police            Slight   
201501BS70005   -0.208327  51.514952    Metropolitan Police            Slight   
201501BS70008   -0.206022  51.496572    Metropolitan Police           Serious   
201501BS70009   -0.193610  51.500788    Metropolitan Police            Slight   
201501BS70010   -0.173519  51.495171    Metropolitan Police            Slight   
201501BS70011   -0.163542  51.492497    Metropolitan Police            Slight   
201501BS70012   -0.211980  51.513659    Metropolitan Police            Slight   
201501BS70013   -0.199786  51.515900    Metropolitan Police            Slight   
201501BS70014   -0.216407  51.518402    Metropolitan Police            Slight   
201501BS70015   -0.184495  51.501726    Metropolitan Police            Slight   
201501BS70016   -0.172522  51.491289    Metropolitan Police            Slight   
201501BS70017   -0.195797  51.492818    Metropolitan Police            Slight   
201501BS70018   -0.166886  51.488143    Metropolitan Police            Slight   
201501BS70019   -0.166882  51.488233    Metropolitan Police            Slight   
201501BS70020   -0.214099  51.514770    Metropolitan Police            Slight   
201501BS70022   -0.183889  51.484361    Metropolitan Police            Slight   
201501BS70023   -0.207725  51.519259    Metropolitan Police            Slight   
201501BS70024   -0.172964  51.491026    Metropolitan Police            Slight   
201501BS70026   -0.163102  51.499864    Metropolitan Police           Serious   
201501BS70027   -0.192941  51.488548    Metropolitan Police            Slight   
201501BS70029   -0.193675  51.488199    Metropolitan Police            Slight   
201501BS70030   -0.215564  51.517850    Metropolitan Police            Slight   
201501BS70033   -0.185515  51.483307    Metropolitan Police            Slight   
201501BS70034   -0.163793  51.496997    Metropolitan Police            Slight   
201501BS70035   -0.158276  51.494483    Metropolitan Police            Slight   
201501BS70036   -0.194671  51.506739    Metropolitan Police            Slight   
201501BS70037   -0.167365  51.483385    Metropolitan Police            Slight   
201501BS70038   -0.167321  51.488060    Metropolitan Police            Slight   
...                   ...        ...                    ...               ...   
2015984126215   -2.957692  55.077345  Dumfries and Galloway            Slight   
2015984126815   -3.293388  54.983052  Dumfries and Galloway            Slight   
2015984126915   -3.283579  55.067857  Dumfries and Galloway            Slight   
2015984127315   -3.246680  54.991664  Dumfries and Galloway            Slight   
2015984127515   -3.254108  54.986752  Dumfries and Galloway            Slight   
2015984127615   -2.966998  55.246691  Dumfries and Galloway            Slight   
2015984128215   -3.128065  55.025147  Dumfries and Galloway             Fatal   
2015984128515   -3.270137  55.064727  Dumfries and Galloway           Serious   
2015984129115   -3.422724  55.276010  Dumfries and Galloway            Slight   
2015984129715   -3.083745  54.996613  Dumfries and Galloway            Slight   
2015984130315   -3.384031  55.338930  Dumfries and Galloway            Slight   
2015984130815   -3.412795  55.326666  Dumfries and Galloway           Serious   
2015984131215   -3.114769  54.992477  Dumfries and Galloway            Slight   
2015984132215   -3.249009  54.986643  Dumfries and Galloway            Slight   
2015984132315   -3.171246  55.009785  Dumfries and Galloway            Slight   
2015984132815   -3.323723  55.093705  Dumfries and Galloway           Serious   
2015984133015   -3.259471  54.987335  Dumfries 

#Save the cleaned data

In [46]:
ds.to_csv(r'C:\Users\mycom\Desktop\DataCleaned.csv')